# Generated by Django 5.0.6 on 2024-05-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=250)),
                ('prazo', models.DateField()),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('NO', 'Nova'), ('AN', 'Em andamento'), ('CO', 'Concluida'), ('CA', 'Cancelada')], max_length=2)),
            ],
        ),
    ]
