# Generated by Django 5.0.6 on 2024-05-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='situacao',
            field=models.CharField(choices=[('NO', 'Nova'), ('AN', 'Em Andamento'), ('CO', 'Concluída'), ('CA', 'Cancelada')], max_length=2),
        ),
    ]
